[tool.poetry]
name = "volumes-docker"
version = "0.1.0"
description = "Python dependencies for the loamg volumes report generation image"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pytest = "*"
frictionless = {version = "*", extras = ["excel", "html"]}
pandas = {version = "*", extras = ["excel", "html"]}
dpm = {git = "https://github.com/splor-mg/dpm.git", branch = "main"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
