name: Publish Image to Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Configure git user
        uses: fregante/setup-git-user@v2
      - name: Install Infisical CLI
        uses: Infisical/setup-cli@v1
      - name: Check for package updates and build if needed
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
        run: |
          infisical run \
            --client-id="$INFISICAL_CLIENT_ID" \
            --client-secret="$INFISICAL_CLIENT_SECRET" \
            --env=dev \
            -- make release
